Add implicit branch creation and other small changes to Readme.md
appliedAI-Initiative/lakefs-spec pull request #48
Opened 2023-08-30 11:31 UTC by maxmynter

As in title. 

Added an explanation of the implicit branch creation and uploading files in general to the `readme.md`

2023-08-30 13:11 UTC, nicholasjng requested changes
Could you just append the bit on writing pandas DataFrames to the pandas example? 

Currently, the bit is too specific to pandas to be its own section, since we do not want to assume the user actually using pandas.

2023-08-30 13:11 UTC, nicholasjng commented on README.md
> +When the target file not exists, it is created. Otherwise, the existing file is updated.
```suggestion
If the target file does not exist, it is created, otherwise, the existing file is updated.
```

2023-08-30 13:11 UTC, nicholasjng commented on README.md
> +If the specified branch does not exist, it is created. This behaviour can be set in the filesystem constructor via the `create_branch_ok` flag:
```suggestion
If the specified branch does not exist, it is created by default. This behaviour can be set in the filesystem constructor via the `create_branch_ok` flag:
```

2023-08-30 13:11 UTC, nicholasjng commented on README.md
> +# The default setting, precheck_files=False disables client-side caching.
This comment is stale / copy-pasted?

2023-08-30 13:11 UTC, nicholasjng commented on README.md
> +To selectively enable or disable automatic commits, client-side caching, or implicit branch creation you can use a `scope` context manager:
```suggestion
To selectively enable or disable automatic commits, client-side caching, or automatic branch creation, you can use a `scope` context manager:
```

2023-08-31 08:33 UTC, maxmynter commented on README.md
> +# The default setting, precheck_files=False disables client-side caching.
jup

2023-08-31 09:01 UTC, nicholasjng requested changes

2023-08-31 09:01 UTC, nicholasjng commented on README.md
> +# The default setting, precheck_files=True enables implicit branch creation
```suggestion
# create_branch_ok=True (the default setting) enables implicit branch creation
```

2023-08-31 09:01 UTC, nicholasjng commented on README.md
> -
Please revert, the space makes it more readable because of the different indentations (imo).

2023-08-31 12:30 UTC, merged